### ISSUE TITLE
Linenumbers break at an equation*

### ISSUE THREAD

**Issue by pfasante** [Cryptosaurus/iacrtrans#1]
In submission mode, the linenumbering breaks when an equation* environment is used.
This seems to be easy to fix, the required code line is already in the class, but commented out. Is there a reason for this?
I prepare a PR that uncomments this line.

Minimal Working Example:
```
\documentclass[submission]{iacrtrans}
\begin{document}
Test
\begin{equation*}
a = b
\end{equation*}
Test
\end{document}
```

**Comment by Cryptosaurus** [comment]
As far as I can tell, the code was commented because (unstared) `equation` works fine, but uncommenting the line `\patchBothAmsMathEnvironmentsForLineno{equation}` makes it slightly worse.  I guess I missed that `equation*` were broken.  The best solution is probably to add `\patchAmsMathEnvironmentForLineno{equation*}` instead.
