### ISSUE TITLE
Caption Misplaced and Missing when Putting Figures Side by Side

### ISSUE THREAD

**Issue by THLO** [Cryptosaurus/iacrtrans#16]
When using minipages to put two figures side by side as in this piece of code

```
\begin{figure}
\centering  
\begin{minipage}{.5\textwidth}
  \centering
  \includegraphics[width=\columnwidth]{image1}
  \captionof{figure}{A figure}
  \label{fig:test1}
\end{minipage}%
\begin{minipage}{.5\textwidth}
  \centering
  \includegraphics[width=\columnwidth]{image1}
  \captionof{figure}{Another figure}
  \label{fig:test2}
\end{minipage}
\end{figure}
```

the **expected outcome** is that the two figures appear next to each other and the two captions are placed underneath.

**What actually happens**: The second caption appears under the first figure and there is no caption for the second figure.

I would greatly appreciate it if this bug was fixed soon. Thanks!

**Comment by Cryptosaurus** [comment]
Hi Thomas,

The recommended way to use side-by-side Figures is with the `floatrow` package (loaded with the `floatrow` option of the iacrtrans class), as explained in the class documentation.  This is because the class uses packages to automatically put the captions above tables and below figures, but this does not work properly when you put several captions in the same figure environment.

Your example can be written as:
```LaTeX
\documentclass[floatrow]{iacrtrans}

\begin{document}

\begin{figure}
  \begin{floatrow}
    \ffigbox{\includegraphics[width=\columnwidth]{image1}}
    {\caption{A figure}}
    \label{fig:test1}
    \ffigbox{\includegraphics[width=\columnwidth]{image1}}
    {\caption{Another figure}}
    \label{fig:test2}
  \end{floatrow}
\end{figure}

\end{document}
```

**Comment by THLO** [comment]
Thanks a lot for the tip! The `floatrow` package is exactly what I needed.
Just a remark: The labels have to defined inside the curly brackets, e.g., `{\caption{A figure}
    \label{fig:test1}}`, otherwise LaTeX can't find the labels (at least in my system).
Thanks again!
