### ISSUE TITLE
Problem with TCHES final issue

### ISSUE THREAD

**Issue by dfaranha** [Cryptosaurus/iacrtrans#29]
Hi,

We are preparing our final version for submission to TCHES 2021-4 due on Wednesday, but we noticed that the build fails when we change the class file options.

We managed to reproduce the issue in the example by replacing `\documentclass[journal=tosc,submission]{iacrtrans}` with `\documentclass[journal=tches,final]{iacrtrans}` in `template.tex`, most likely due to a package conflict:

`! Package totpages Error: Can't use both, lastpage and totpages.`

Are we doing something wrong, and is there any known workarounds for this problem?

Thank you!

**Comment by Cryptosaurus** [comment]
Hi Diego,
I believe this an issue with recent versions of hyperxmp, it should have been fixed in commit 5629db4. Can you check that you have the latest version of the iacrtrans class?
If it still doesn't work, please tell us what LaTex distribution you are using, and include the output log file (on my machine the template compiles correctly with `[journal=tches,final]`).

**Comment by dfaranha** [comment]
That solves the problem, thank you!

It turns out we're not using the latest version of the iacrtrans class because we missed the recent release. :)
