### ISSUE TITLE
Got Warning 'This document may violate the submission format requirements'

### ISSUE THREAD

**Issue by yberlin** [Cryptosaurus/iacrtrans#35]
This document may violate the submission format requirements
Submissions that violate the requirements will not be considered. However, some violation reports may be false positives (for instance, the checker can miscalculate margins and text sizes for figures). If you are confident that the current document respects all format requirements, keep it as is.
Margins too small: text width exceeds 159mm by 32% (page 1)
Margins too small: text height exceeds 246mm by 21% (page 1)

My colleague and I used the template files and complied the different paper, then submitted the pdf to system, separately. We both get this warning with same value of (159 mm) and (246 mm). Is this a false positives for both of us? Or the template files are updated?

**Comment by kmccurley** [comment]
This is almost certainly a problem in hotcrp rather than the `iacrtrans` document class. There are no checks in the document class, but hotcrp uses a ]`banal`](https://github.com/IACR/hotcrp/blob/master/src/banal) script. Note that the IACR instances of hotcrp have this disabled by default, so perhaps a chair turned it on. The reason why it is disabled is because I didn't trust it.

Note that I am no longer making changes to hotcrp.
